<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-29 16:15
=======
# Generated by Django 5.2.14 on 2026-05-28 22:50
>>>>>>> b673fa0a2f578d336e17974dd3669d014a1c67e7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('pin_hash', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
=======
>>>>>>> b673fa0a2f578d336e17974dd3669d014a1c67e7
            ],
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('full_name', models.CharField(max_length=100)),
                ('punch_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='attendance.employee')),
=======
                ('punch_type', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
>>>>>>> b673fa0a2f578d336e17974dd3669d014a1c67e7
            ],
        ),
    ]
